# Name: Gnanitha Suryadevara
# Course: SWE 645 - HW3
# Purpose: Nginx config for React frontend

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
